### ISSUE TITLE
Remove Brewers Association import task

### ISSUE THREAD

**Issue by chrisjm** [openbrewerydb/openbrewerydb-rails-api#17]
It's fairly irrelevant now that there's a CSV export included in the repository.

**Comment by chrisjm** [comment]
Need to add a new import task before removing the old one. See #27

**Comment by Johnnyk737** [comment]
I think we can remove this now that we have a PR addressing this.

**Comment by chrisjm** [comment]
Good call. Thanks @Johnnyk737 ! 🍻
