### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by chrisjm** [openbrewerydb/openbrewerydb-rails-api#18]
- [x] Reindexing Elasticsearch
- [x] ~~Heroku deploy: https://devcenter.heroku.com/articles/heroku-button~~ I don't think this is actually necessary
- [x] Rails version

## Gemfile

- [x] Add versions to avoid confusion

**Comment by Johnnyk737** [comment]
https://github.com/openbrewerydb/openbrewerydb-rails-api/pull/68 should address reindexing ElasticSearch. https://github.com/openbrewerydb/openbrewerydb-rails-api/pull/69 will address Gemfile versions. I can add Rails version to it.
