### ISSUE TITLE
Import task for breweries CSV

### ISSUE THREAD

**Issue by chrisjm** [openbrewerydb/openbrewerydb-rails-api#27]
## Overview

Add import task for `db/breweries.csv`. This will replace the old method of import via the Brewers Association scraped HTML files.

## Tasks

- [ ] Create new import task in `app/services/import/`

## Related issues

#17 #23

**Comment by Johnnyk737** [comment]
I can take this one

**Comment by chrisjm** [comment]
Thanks @Johnnyk737 !

Instead of using a file in the repo, what about grabbing directly from https://raw.githubusercontent.com/openbrewerydb/openbrewerydb/master/breweries.csv ?

**Comment by Johnnyk737** [comment]
I had the same thought! Although I was thinking of using the JSON format of data. I'd want to look into creating an ActiveRecord object from a CSV. I've not done that before.

**Comment by Johnnyk737** [comment]
I've got a branch set up with some initial changes. The good news is that it works! The bad news is, when you run the import task, it takes about 1 second for each brewery to be imported. This obviously adds up to a ton of time and is unreasonable for local development. I would like to research more on how to speed this up, but I'd like to hear your thoughts. 

https://github.com/Johnnyk737/openbrewerydb-rails-api/tree/OBDB-27

**Comment by chrisjm** [comment]
Oh man, my Ruby is rusty 😅  My guess is that the lag is likely from the query and then the update, though 1s is still rather long (500ms maybe). You might be able to get around making two transactions, but I'm not exactly sure how with ActiveRecord.

Could you create a work in progress PR so that I can make some notes via the review tool?

Thanks so much for working on this stuff, @Johnnyk737 ! 🍻

**Comment by Johnnyk737** [comment]
Done https://github.com/openbrewerydb/openbrewerydb-rails-api/pull/68

**Comment by Johnnyk737** [comment]
I was able to speed this up so each brewery takes ~500ms by removing the `.save` for each new brewery. It is already using `create` which does a `new` then `save` already, so this was duplicated work. I've also batched them, but that didn't save any time. 

It's worth noting I'm on a windows machine using WSL2. This may end up being faster on a mac or linux machine.

**Comment by chrisjm** [comment]
Awesome! 

I attempted to test but ran into the following error:

`ActiveRecord::RecordInvalid: Validation failed: Obdb has already been taken`

I'll dig into the code and figure out what's going on this evening.

**Comment by Johnnyk737** [comment]
That is happening because I'm currently not doing any existence checks. Your breweries table is full up already. If you truncate, then run the rake task, you should see it load fine.

**Comment by Johnnyk737** [comment]
I was just thinking, for local development, you may not need to seed the db with all 7k breweries. Do you think we can get away with loading only a few hundred? This is assuming you have another job that builds the hosted database.

**Comment by chrisjm** [comment]
Re: local development, I think seeding with all breweries would be ideal for manual testing and investigation. That said, might be worth it to provide options/arguments to give developers flexibility depending on their use case.

Also worth considering if using ActiveRecord is really the right path. The dataset also includes a SQL file. It's specific to Postgres but takes seconds to run.

And finally, what about truncating the database as a first step? Maybe after a prompt?

These are all just thoughts and suggestions, so feel free to push back on any or all of them. :)  

Thank you for putting time and effort into this! 🍻

**Comment by Johnnyk737** [comment]
So, a few things.

- The geocoding after validation is what is draining performance. Removing that single line sped it up a TON. 
- Elastic search also slows this down, but not nearly as much as Geocoder.
- For ~7k breweries
  - Without geocode: ~114 seconds
  - Without geocode and ES: ~25 seconds
  - With Geocode: Somewhere between 7000 seconds and Infinity (estimate)
- Import by SQL with rake works great. It's super fast (~1 second) and really easy to implement. However, this bypasses all validations, geocoding and ES. There is an existing rake task to update the geocodes, so maybe that is the route we want to go. Geocoder also has one that allows batch updating (`rake geocode:all CLASS=Brewery BATCH=100`). 

Where we go from here depends on a few things (start idea vomit):
- If we insert by SQL, we require truncating first. It would be a non-trivial effort to parse through an sql string and figure out which ones exist already. However, I think we could make this a logic gate using an env though and use the json mapping way if we don't want to truncate (if TRUNCATE=true ? insert by sql : insert by json). Assuming, we have new contributors doing this, maybe truncate by default? Maybe the env would be UPDATE and if true, it would only add new breweries. I've updated my draft PR so you can take a look at this implementation.
- I'm not sure the validation is necessary here either. For now, all of the validation is done elsewhere when we are creating the data. Importing that data into a local environment and then doing validation seem redundant. However, outside of the geocoding, validation performance is trivial, so I'm not super concerned.
- There are plans to remove ES already, so I'm not going to worry about speeding it up or removing that now.
- Geocoding is obviously important here but performance is a huge concern. I'm not sure this is super important for local development though, unless you are testing the `by_distance` endpoint. At that point, I think it would be best to find and insert only breweries needed for that specific testing. When deploying though, we can run the geocode task and let it run and run and run.

**Comment by chrisjm** [comment]
Awesome! Thanks for testing those things out. 

* Yes, let's ditch requiring Geocoding and ES index building while doing the imports. Those should definitely be separate tasks.
* Totally down with making the `TRUNCATE=true` an environment flag and ditching extra validation other than simple "this should be a number, this should a string, this is an enum, etc."
* I'm actually surprised the geocoding takes so long to run. I don't think it took that long when I was implementing things so maybe it's getting hung up on something else. In any case, that investigative work is outside the scope of this task. Setting things up so that it runs as a separate, explicit task makes the most sense to me.

**Comment by Johnnyk737** [comment]
Sounds great, I'll add docs to manage the other tasks. All of them are created already, just a matter of documenting them out. I'll also mark the PR as ready for review.

**Comment by chrisjm** [comment]
Closed by #68
