### ISSUE TITLE
RFC: Move from relational to document store database?

### ISSUE THREAD

**Issue by chrisjm** [openbrewerydb/openbrewerydb-rails-api#34]
# Discussion

## Reasoning

- In discussing a way to allow for community-driven dataset updates, I had a thought to create another repository with a collection of JSON files (probably organized by country then state/providence) which could then be compiled and update a DB via Github Actions or another CI/CD process. With this process, it would likely be easier to update a DB like Mongo or DynamoDB. 

## To Research 📚 

- [x] Is ~key-value~ Document Store / NoSQL database able to do location-based queries like PostGIS?
  - https://github.com/chrisjm/openbrewerydb-rails-api/issues/34#issuecomment-575385527
  - [MongoDB Geospatial Queries](https://docs.mongodb.com/manual/geospatial-queries/)

#### Pros

👍  Able to perform more complicated queries such as the full-text search and PostGIS / geospatial searching (not fully researched; key-value might be able to do this as well)
👍  Relational databases are more robust for data management

#### Cons

👎  Somewhat complicated to set up
👎  Expensive (~$180/year with AWS RDS reserved)

#### Pros

👍  Easier to set up from a development standpoint
👍  Cheaper (<$12/year, with current stats; maybe even free)
👍  Can be very performant if data is organized properly

**Comment by holitics** [comment]
I've done some preliminary investigation (no testing yet) and it does seem that geospatial queries can be implemented on DynamoDB.

**Comment by chrisjm** [comment]
@holitics Thank you! Can you provide a reference link?

**Comment by jpthompson212** [comment]
@chrisjm I'm going to work on protyping this out with mongodb.  I'll keep you updated with progress.

**Comment by chrisjm** [comment]
Awesome @jpthompson212! Let me know if there's anything I can do to help!

**Comment by chrisjm** [comment]
We've decided to stick with a relational database for this particular incarnation of the API. v2 may allow for different data stores.
