### ISSUE TITLE
Better caching

### ISSUE THREAD

**Issue by chrisjm** [openbrewerydb/openbrewerydb-rails-api#35]
# Feature request

## Overview

We need better caching.

<img width="1015" alt="Screenshot 2020-02-12 10 41 26" src="https://user-images.githubusercontent.com/96110/74366454-e74fa600-4d84-11ea-8f19-635b9e7df279.png">

## Tasks

???

**Comment by Johnnyk737** [comment]
Are these all just postgresql selects or is there something else going on? Can we see a breakdown of what that bandwith means?

**Comment by chrisjm** [comment]
@Johnnyk737 This is a screenshot of Cloudflare, so these are HTTP requests and bandwidth transferred (which is only JSON).

This whole issue could use a lot more detail, so I'll work on that.

**Comment by chrisjm** [comment]
I'm an idiot and think I finally figured this out via [this StackOverflow](https://stackoverflow.com/a/11570775) and setting Cloudflare Page Rules

```
api.openbrewerydb.org/*
Cache Level: Cache Everything
```

Seeing a decent bump in cached requests in Cloudflare and a decrease in requests in Heroku. Closing for now.
