### ISSUE TITLE
BUG: List breweries sorting; `+` not working as expected

### ISSUE THREAD

**Issue by vshagur** [openbrewerydb/openbrewerydb-rails-api#42]
# Bug Report

## Describe the bug

The documentation for api does not correctly indicate the direction of sorting

## Steps to reproduce bug

1. Go to 'https://www.openbrewerydb.org/documentation/01-listbreweries'
2. We look at the sorting section.
3. Copy the link from the [second example](https://api.openbrewerydb.org/breweries?by_city=san_diego&sort=-name) and send the request.
4. We get the result in descending order. 

### Expected behavior
We expect the result in ascending order. The documentation says: _**"- for ascending order (default)"**_

## Screenshots
[screenshots_1](https://ibb.co/d586k7Q), [screenshots_2](https://ibb.co/CWG62C9), 

### Desktop

- OS: [Linux Samsung 4.9.0-8-amd64 chrisjm/openbrewerydb-gatsby#1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linu]
- Browser [Chromium]
- Version [Версия 73.0.3683.75 (Сборка для разработчиков), built on Debian 9.8, running on Debian 9.11 (64 бит)]

## Smartphone
None
## Additional context

In addition to the error with the direction of sorting in the description, there is no clarity. You may get the impression that you need to use the "+" key to sort in ascending order. I suggest that you explicitly indicate that you do not need to use the "+" key and add an example of a default sorting link (now there is only a combined case for two fields in the description). Using the "+" key in a query leads to an incorrect result.[ Screenshot](https://ibb.co/N60xZJY).

**Comment by Johnnyk737** [comment]
> It looks like there is an actual bug 

Just looking into this, I'm not able to reproduce that bug currently. Using the above example.

URL: http://localhost:3000/breweries?by_city=san_diego&sort=+name

['10 Barrel Brewing Co', '2Kids Brewing Company', '32 North Brewing Co', 'Abnormal Beer Company', 'Acoustic Ales Brewing Experiment', 'AleSmith Brewing Co', 'Align Brewing Co', 'Alpine Beer Company', 'Alta Brewing Company', 'Amplified Ale Works', 'Amplified Ale Works Miramar Studio', 'Automatic Brewing Co. / Blind Lady Alehouse', 'Ballast Point Brewing Co / Home Brew Mart', 'Ballast Point Brewing Company', 'Ballast Point Brewing Company', 'Ballast Point Brewing Company - Little Italy', 'Barn Brewery', 'Bay City Brewing Co.', 'Benchmark Brewing Co', 'Bitter Brothers Brewing Co.']

URL: http://localhost:3000/breweries?by_city=san_diego&sort=-name

['White Labs Tasting Room', 'Thunderhawk Alements', 'Thorn Street Brewery', 'Thorn Brewing Co', 'The Bell Marker', 'Tenacious Brewing Company', 'Stover Brewing', 'Stone Brewing World Bistro & Gardens- Liberty Station', 'South Park Brewing', 'Societe Brewing Company', 'Second Chance Beer Company', 'Savagewood Brewing Company', 'San Diego Brewing Co', 'Saint Archer Brewing Company', 'Rough Draft Brewing', 'Rip Current Brewing North Park', 'Resident Brewing', 'Quantum Brewing Co', 'Pure Project', 'Protector Brewery']

**Comment by vshagur** [comment]
Hello Johnnyk737. Please take a look at the [documentation](https://www.openbrewerydb.org/documentation/01-listbreweries).
```
sort
Sort the results by one or more fields.

- for ascending order (default)
+ for decending order
```

The "+" key should sort in descending order (from highest to lowest). The data in the response is sorted in ascending order (from lowest to highest). We observe the opposite behavior of the system than what is described in the documentation.

**Comment by chrisjm** [comment]
Thank you @Johnnyk737 for testing and @vshagur for the clarification.

Overall, the `+` and `-` are confusing and we should use `asc` and `desc`. 

In the meantime, I've updated the documentation to the following:

> Sort the results by one or more fields.
> 
> - `+` for ascending order
> - `-` for decending order

🍻
