### ISSUE TITLE
adding sorting to filtering queries changes the list of returned items

### ISSUE THREAD

**Issue by vshagur** [openbrewerydb/openbrewerydb-rails-api#43]
# Bug Report

## Describe the bug

adding sorting to filtering queries changes the list of returned items

## Steps to reproduce bug

1. We will make a request for receiving data with a filter by name with the value "town" - [https://api.openbrewerydb.org/breweries?by_name=town](https://api.openbrewerydb.org/breweries?by_name=town)
2. We repeat the previous query, but with the addition of sorting by name - [https://api.openbrewerydb.org/breweries?by_name=town&sort=name](https://api.openbrewerydb.org/breweries?by_name=town&sort=name)
3. Compare the id brewing of the first request with the second. 
First - 
[189, 398, 535, 618, 624, 735, 736, 880, 926, 975, 1067, 1134, 1328, 2338, 2476, 3663, 3802, 6245, 7601, 7674]
Second - 
[398, 2338, 2740, 3107, 3247, 3802, 3984, 4675, 5054, 5660, 5661, 5740, 5749, 6000, 6046, 6387, 7339, 7358, 7758, 7802]

We see that the second query returned a different list of breweries.

### Expected behavior

When the api user adds sorting to filtering requests, he expects to receive exactly the same data set, but sorted by the field defined by him. This is a natural behavior. This natural behavior can be seen in search queries and autocompletion queries. For example queries - 
[https://api.openbrewerydb.org/breweries/autocomplete?query=town](https://api.openbrewerydb.org/breweries/autocomplete?query=town) and 
[https://api.openbrewerydb.org/breweries/autocomplete?query=town&sort=name](https://api.openbrewerydb.org/breweries/autocomplete?query=town&sort=name) will return the same list - [ '624', '2338', '2524', '2688', '2922', '3584', '3984', '5183', '5895', '5906', '6387', '6827', '7615', '7749', '7765']

## Screenshots
[The natural behavior.](https://ibb.co/GT6sFJy)
[Bug.](https://ibb.co/Fz4FhHq)

### Desktop

- OS: [Linux Samsung 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linu]
- Browser [Chromium]
- Version [Версия 73.0.3683.75 (Сборка для разработчиков), built on Debian 9.8, running on Debian 9.11 (64 бит)]

## Smartphone

- None

## Additional context

- None

**Comment by chrisjm** [comment]
After reading through this bug again, I think this may actually be expected behavior. While it may not look like it's returning the same results, I believe the pagination is causing the confusion. Additionally, the `autocomplete` endpoint doesn't currently have a sort feature.
