### ISSUE TITLE
Add ability to exclude `by_type`

### ISSUE THREAD

**Issue by chrisjm** [openbrewerydb/openbrewerydb-rails-api#44]
# Overview

Use case: "I am trying to get a list of all the breweries in Austin, TX that are not in "Planning" type"

# Implementation Notes

- `exclude_types` parameter name?
- Multiple types may be included via comma-separation (ex. `?exclude_types=planning,regional`)

**Comment by Johnnyk737** [comment]
I'd like to take a shot at this. Are we expecting since the proposed param name is plural, that we'd allow multiple excluded types?

(I'm schmarv21 on discord btw)

**Comment by chrisjm** [comment]
@Johnnyk737 Sounds great! And yes, multiple types should be accepted via comma-separated. I'll update the description as well.

**Comment by Johnnyk737** [comment]
Ok great. Btw, can you assign this issue to me? I don't seem to have access to do so.

**Comment by Johnnyk737** [comment]
PR https://github.com/openbrewerydb/openbrewerydb-rails-api/pull/61

**Comment by chrisjm** [comment]
You rock @Johnnyk737 ! 🍻  Fixed by #61
