### ISSUE TITLE
Update `sort` filter to use `asc` and `desc` parameters

### ISSUE THREAD

**Issue by chrisjm** [openbrewerydb/openbrewerydb-rails-api#62]
# Feature request

## Overview

The current `+` and `-` parameters for sorting are succinct and fancy, but very confusing. Let's instead use `asc` and `desc` which is more inline with database vocabulary.

* Pros - Easier to understand
* Cons - We lose the ability to sort by multiple features, though I'm not sure that worked anyway.

**Comment by chrisjm** [comment]
Related to #42

**Comment by Johnnyk737** [comment]
I can take up this change.

**Comment by chrisjm** [comment]
@Johnnyk737 You got it! Thank you! 🍻

**Comment by Johnnyk737** [comment]
In keeping the same style as before where the prefix is the sort param, should we have something like `asc_name`? Do we have a preference on how this new param should look?

**Comment by chrisjm** [comment]
What about something like: `https://api.openbrewerydb.org/breweries?by_state=ohio&sort=type,name:desc`?

Also what about the default sort order? In more numeric-driven data, I think the preference tends to be for default to be `desc`. But since this is mostly categorical data, `asc` tends to be what people want. Thoughts?

**Comment by Johnnyk737** [comment]
I'm not a huge fan of using colons in query parameters. It is generally fine, but in some cases it would require extra decoding if it's part of the query string. I don't mind either way though. We just need to let consumers know this information so they can change their implementation a bit (which they would have to do anyways)

For now, I think the default should be `asc`. As you say, it's more categorical and more alpha than numeric. However, as we enhance the API and data points, I think we can make different default sorts. For example, if we are looking at breweries in the area and want to see when they opened up, the best sort order for default would be `desc` by opened date/time. However, if we just want to search by area or city, we'd probably stick to `asc` by name.

**Comment by chrisjm** [comment]
I'm not a huge fan of the underscore separator since underscores are also used in the parameter/fitler names, so this kind of looks weird to me:

`https://api.openbrewerydb.org/breweries?by_state=ohio&sort=type,desc_name`, or 
`https://api.openbrewerydb.org/breweries?by_state=ohio&sort=type,name_desc`

I'm open to other suggestions. Maybe it's as simple as only allowing sorting by one feature and adding an `order` filter? I only took a sample of two other free APIs (Punk API and Dog API), but those don't even offer sorting, so 🤷 .

**Comment by Johnnyk737** [comment]
How do we feel about a `|`? Like `name|desc`. 

I don't want to take away multiple sorting parameters. I think it's great that you put that in.

**Comment by chrisjm** [comment]
I did a little bit of research to see how others were suggesting designing this kind of API feature and found a few resources:

- https://www.taniarascia.com/rest-api-sorting-filtering-pagination/#multiple-columns
- https://www.moesif.com/blog/technical/api-design/REST-API-Design-Filtering-Sorting-and-Pagination/#sorting
- https://www.mscharhag.com/api-design/collection-sorting

### Examples from Articles

- `GET /users?sort=first_name:asc,age:desc`
- `GET /users?sort_by=desc(last_modified),asc(email)`
- `GET /users?sort_by=-last_modified,+email`
- `GET /products?sort=price:asc,name:desc`
- `GET /products?sort=price:asc&sort=name:desc`

I'd be good with any of these implementations (some are the same, I just copy+pasted).

**Comment by Johnnyk737** [comment]
Fair enough :) In other APIs at my current position, we use colons in the query parameter names so I'm much more used to those. I much prefer the first way with `field:sort`. The last also is good but I'd like to keep a similar implementation as before.
